//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//  Refactoring by @Alhazmy13
//

import UIKit

protocol ___FILEBASENAMEASIDENTIFIER___ServiceInput {
  func doSomething(request: ___FILEBASENAMEASIDENTIFIER___Request)
}

protocol ___FILEBASENAMEASIDENTIFIER___ServiceOutput {
  func presentSomething(response: ___FILEBASENAMEASIDENTIFIER___Response)
}

protocol ___FILEBASENAMEASIDENTIFIER___Repository {
  func doSomeWork()
}

class ___FILEBASENAMEASIDENTIFIER___Service: ___FILEBASENAMEASIDENTIFIER___ServiceInput {
  var output: ___FILEBASENAMEASIDENTIFIER___ServiceOutput!
  var repoImpl: ___FILEBASENAMEASIDENTIFIER___RepoImpl!
  
  // MARK: Business logic
  
  func doSomething(request: ___FILEBASENAMEASIDENTIFIER___Request) {
    // NOTE: Create some Worker to do the work
    
    repoImpl = ___FILEBASENAMEASIDENTIFIER___RepoImpl()
    repoImpl.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = ___FILEBASENAMEASIDENTIFIER___Response()
    output.presentSomething(response)
  }
}

